apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: controlplane
  namespace: openstack
spec:
  neutron:
    enabled: true
    template:
      customServiceConfig: |
        [DEFAULT]
        debug = True
