apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: dep-pre-ceph
  namespace: openstack
spec:
  nodeSets:
    - openstack-edpm-ipam
  servicesOverride:
    - repo-setup-custom
    - bootstrap
    - configure-network
    - validate-network
    - install-os
    - ceph-hci-pre
    - configure-os
    - run-os
