#
# Change the fields below for certain interfaces and IPs to match your environment.
# "spec.desiredState.interfaces" can be added to support additional networks.
#

apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    osp/interface: eno1 # CHANGEME
  name: eno1-osp4 # CHANGEME
spec:
  desiredState:
    dns-resolver:
      config:
        search: []
        server:
        - 192.168.24.1 # CHANGEME
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.24.1 # CHANGEME
        next-hop-interface: eno1 # CHANGEME
    interfaces:
    - description: internalapi vlan interface
      ipv4:
        address:
        - ip: 172.17.1.7
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: eno1.301 # CHANGEME
      state: up
      type: vlan
      vlan:
        base-iface: eno1 # CHANGEME
        id: 301
    - description: storage vlan interface
      ipv4:
        address:
        - ip: 172.17.3.7
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: eno1.302 # CHANGEME
      state: up
      type: vlan
      vlan:
        base-iface: eno1 # CHANGEME
        id: 302
    - description: tenant vlan interface
      ipv4:
        address:
        - ip: 172.17.2.7
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: eno1.304 # CHANGEME
      state: up
      type: vlan
      vlan:
        base-iface: eno1 # CHANGEME
        id: 304
    - description: Configuring eno1 # CHANGEME
      ipv4:
        address:
        - ip: 192.168.24.12 # CHANGEME
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: eno1 # CHANGEME
      state: up
      type: ethernet
  nodeSelector:
    kubernetes.io/hostname: ospperf4.mobius.lab.eng.rdu2.redhat.com # CHANGEME
    node-role.kubernetes.io/worker: ""
